Race.create(name: "Gnome")
Race.create(name: "Human")
Race.create(name: "Night Elf")
Race.create(name: "Draenei")
Race.create(name: "Worgen")
Race.create(name: "Dward")
Race.create(name: "Tauren")
Race.create(name: "Troll")
Race.create(name: "Undead")
Race.create(name: "Blood Elf")
Race.create(name: "Goblin")
Race.create(name: "Orc")
Race.create(name: "Pandaren")