Race.create(name: "Gnome")
Race.create(name: "Human")
Race.create(name: "Night Elf")
Race.create(name: "Draenei")
Race.create(name: "Worgen")
Race.create(name: "Dward")
Race.create(name: "Tauren")
Race.create(name: "Troll")
Race.create(name: "Undead")
Race.create(name: "Blood Elf")
Race.create(name: "Goblin")
Race.create(name: "Orc")
Race.create(name: "Pandaren")

CharacterClass.create(name: "Druid")
CharacterClass.create(name: "Hunter")
CharacterClass.create(name: "Mage")
CharacterClass.create(name: "Paladin")
CharacterClass.create(name: "Priest")
CharacterClass.create(name: "Rogue")
CharacterClass.create(name: "Shaman")
CharacterClass.create(name: "Warlock")
CharacterClass.create(name: "Warrior")
CharacterClass.create(name: "Death Knight")
CharacterClass.create(name: "Monk")
CharacterClass.create(name: "Demon Hunter")

Profession.create(name: "Alchemist")
Profession.create(name: "Blacksmith")
Profession.create(name: "Enchanter")
Profession.create(name: "Engineer")
Profession.create(name: "Herbalism")
Profession.create(name: "Inscription")
Profession.create(name: "Jewelry Crafter")
Profession.create(name: "Leatherworker")
Profession.create(name: "Miner")
Profession.create(name: "Skinner")
Profession.create(name: "Tailor")